version: '3'

services:
  spalliandex:
    container_name: spalliandex
    image: spalliandex:latest
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
