version: "3.8"

services:
  app:
    container_name: app
    working_dir: /app
    image: app
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000